/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AssetDemand: typeof import('./src/components/back/AssetDemand.vue')['default']
    AssetEdit: typeof import('./src/components/back/AssetEdit.vue')['default']
    AssetMeeting: typeof import('./src/components/back/AssetMeeting.vue')['default']
    AssetPlan: typeof import('./src/components/back/AssetPlan.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
