/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/back/AssetManage': RouteRecordInfo<'/back/AssetManage', '/back/AssetManage', Record<never, never>, Record<never, never>>,
    '/back/Dashboard': RouteRecordInfo<'/back/Dashboard', '/back/Dashboard', Record<never, never>, Record<never, never>>,
    '/back/DemandManage': RouteRecordInfo<'/back/DemandManage', '/back/DemandManage', Record<never, never>, Record<never, never>>,
    '/back/Login': RouteRecordInfo<'/back/Login', '/back/Login', Record<never, never>, Record<never, never>>,
    '/back/MeetingManage': RouteRecordInfo<'/back/MeetingManage', '/back/MeetingManage', Record<never, never>, Record<never, never>>,
    '/back/PlanManage': RouteRecordInfo<'/back/PlanManage', '/back/PlanManage', Record<never, never>, Record<never, never>>,
    '/back/Template': RouteRecordInfo<'/back/Template', '/back/Template', Record<never, never>, Record<never, never>>,
    '/front/Home': RouteRecordInfo<'/front/Home', '/front/Home', Record<never, never>, Record<never, never>>,
    '/front/PublicAssetDetail': RouteRecordInfo<'/front/PublicAssetDetail', '/front/PublicAssetDetail', Record<never, never>, Record<never, never>>,
    '/front/PublicAssetList': RouteRecordInfo<'/front/PublicAssetList', '/front/PublicAssetList', Record<never, never>, Record<never, never>>,
    '/front/PublicDemandForm': RouteRecordInfo<'/front/PublicDemandForm', '/front/PublicDemandForm', Record<never, never>, Record<never, never>>,
    '/front/Template': RouteRecordInfo<'/front/Template', '/front/Template', Record<never, never>, Record<never, never>>,
  }
}
